language: node_js
node_js:
  - "8"
cache:
  yarn: true

jobs:
  include:
    - stage: Test
      node_js: node
      script: "yarn lint"
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: Build
      node_js: "8"
      script: "yarn build"
